#ifndef CONFIG_USER_H
#define CONFIG_USER_H

#define DEBOUNCE 5

#define LEADER_TIMEOUT 250
#define LEADER_PER_KEY_TIMING

#define TAPPING_TERM 200

#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_NUMERIC
#define NO_AUTO_SHIFT_ALPHA

#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPS

#define ONESHOT_TAP_TOGGLE 3
#define ONESHOT_TIMEOUT 5000

#endif
